name: ASP.NET Core CI

on: [push]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - name: Build with dotnet
      run: dotnet build ./src/GitHubActionsDemo.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./src/GitHubActionsDemo.sln --configuration Release
